CREATE TABLE `catalog_products` (
	`id` varchar(64) NOT NULL,
	`name` varchar(255) NOT NULL,
	`nameEn` varchar(255),
	`sku` varchar(120) NOT NULL,
	`category` varchar(120) NOT NULL,
	`brand` varchar(160),
	`vendor` varchar(255) NOT NULL,
	`vendorId` varchar(64) NOT NULL,
	`price` int NOT NULL,
	`originalPrice` int,
	`unit` varchar(120) NOT NULL,
	`minOrder` int NOT NULL DEFAULT 1,
	`stock` int NOT NULL DEFAULT 0,
	`sold` int NOT NULL DEFAULT 0,
	`status` enum('active','inactive','pending_review','rejected','out_of_stock') NOT NULL DEFAULT 'pending_review',
	`images` json NOT NULL,
	`shortDesc` text,
	`longDesc` text,
	`highlights` json,
	`specs` json,
	`usageInstructions` json,
	`certifications` json,
	`tags` json,
	`rating` int NOT NULL DEFAULT 0,
	`reviewCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `catalog_products_id` PRIMARY KEY(`id`),
	CONSTRAINT `catalog_products_sku_unique` UNIQUE(`sku`)
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` int AUTO_INCREMENT NOT NULL,
	`openId` varchar(64) NOT NULL,
	`name` text,
	`email` varchar(320),
	`loginMethod` varchar(64),
	`role` enum('user','admin') NOT NULL DEFAULT 'user',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastSignedIn` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_openId_unique` UNIQUE(`openId`)
);
