import { Link, useParams } from "wouter";
import { AlertCircle, ArrowLeft, BookOpen, Building2, Code2, FileText, HeartHandshake, HelpCircle, Leaf, Newspaper, PackageCheck, Scale, ShieldCheck, Sprout, Truck, UsersRound } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ScrollToTop from "@/components/ScrollToTop";
import { getFooterInfoPage } from "@/lib/footerInfoPages";

const PAGE_ICONS = { about: Sprout, how: Leaf, stories: Newspaper, careers: UsersRound, guide: BookOpen, vendor: PackageCheck, b2b: Building2, provider: HeartHandshake, enterprise: Building2, api: Code2, help: HelpCircle, returns: PackageCheck, shipping: Truck, terms: Scale, privacy: ShieldCheck };

export default function FooterInfoPage() {
  const { slug = "" } = useParams<{ slug: string }>();
  const page = getFooterInfoPage(slug);

  if (!page) return <div className="min-h-screen bg-[#F8F6F0]" dir="rtl"><Navbar /><main className="container flex min-h-[60vh] items-center justify-center pt-28"><div className="max-w-md text-center"><AlertCircle className="mx-auto h-12 w-12 text-[#C9A227]" /><h1 className="mt-4 text-2xl font-black text-[#263238]">لم نعثر على هذه الصفحة</h1><p className="mt-2 text-sm leading-7 text-[#617168]">يمكنك العودة إلى الصفحة الرئيسية أو استكشاف السوق والخدمات المتاحة.</p><Link href="/" className="mt-6 inline-flex rounded-xl bg-[#1F4D3A] px-5 py-3 text-sm font-bold text-white">العودة للرئيسية</Link></div></main><Footer /></div>;

  const Icon = PAGE_ICONS[page.icon];
  const isExternal = page.cta.href.startsWith("mailto:");

  return <div className="min-h-screen bg-[#F8F6F0]" dir="rtl"><Navbar /><main><section className="relative overflow-hidden bg-[#173E30] py-14 sm:py-20"><div className="pointer-events-none absolute inset-0 opacity-25" style={{ backgroundImage: "radial-gradient(circle at 15% 10%, #93BE86 0, transparent 26%), radial-gradient(circle at 90% 90%, #C9A227 0, transparent 30%)" }} /><div className="container relative max-w-4xl"><div className="inline-flex items-center gap-2 rounded-full border border-[#C9A227]/35 bg-[#C9A227]/10 px-3 py-1 text-xs font-bold text-[#F4D889]"><Icon className="h-3.5 w-3.5" />{page.eyebrow}</div><h1 className="mt-5 max-w-3xl text-3xl font-black leading-tight text-white sm:text-5xl">{page.title}</h1><p className="mt-5 max-w-2xl text-base leading-8 text-[#D4E4D5] sm:text-lg">{page.summary}</p></div></section><section className="container max-w-6xl py-10 sm:py-14"><div className="grid gap-5 md:grid-cols-3">{page.sections.map((section, index) => <article key={section.title} className="rounded-2xl border border-[#E1E9DD] bg-white p-6 shadow-[0_3px_16px_rgba(31,77,58,0.05)]"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#EAF5E7] text-sm font-black text-[#1F6B45]">{index + 1}</span><h2 className="mt-5 text-lg font-black text-[#263238]">{section.title}</h2><p className="mt-3 text-sm leading-7 text-[#64736A]">{section.body}</p><ul className="mt-5 space-y-2">{section.points.map((point) => <li key={point} className="flex items-start gap-2 text-sm text-[#34473B]"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[#C9A227]" />{point}</li>)}</ul></article>)}</div><div className="mt-8 flex flex-col items-start justify-between gap-5 rounded-2xl bg-[#F0F5EC] p-6 sm:flex-row sm:items-center"><div><h2 className="text-xl font-black text-[#263238]">خطوتك التالية</h2><p className="mt-1 text-sm text-[#617168]">{page.cta.note}</p></div>{isExternal ? <a href={page.cta.href} className="inline-flex items-center gap-2 rounded-xl bg-[#1F4D3A] px-5 py-3 text-sm font-bold text-white transition-colors hover:bg-[#123528]">{page.cta.label}<ArrowLeft className="h-4 w-4" /></a> : <Link href={page.cta.href} className="inline-flex items-center gap-2 rounded-xl bg-[#1F4D3A] px-5 py-3 text-sm font-bold text-white transition-colors hover:bg-[#123528]">{page.cta.label}<ArrowLeft className="h-4 w-4" /></Link>}</div><p className="mt-8 flex items-start gap-2 rounded-xl border border-[#E5E1D6] bg-white px-4 py-3 text-xs leading-6 text-[#68766D]"><FileText className="mt-0.5 h-4 w-4 shrink-0 text-[#5D896E]" />هذه الصفحة معلوماتية وإرشادية؛ قد تختلف التفاصيل النهائية وفق ما يظهر في رحلة الطلب أو الحجز أو التفعيل ذات الصلة.</p></section></main><Footer /><ScrollToTop /></div>;
}
