import { ArrowRight, MapPin, MessageCircle, ShieldCheck, UserRound } from "lucide-react";
import { Link, useParams } from "wouter";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { trpc } from "@/lib/trpc";

export default function ProviderProfile() {
  const { id } = useParams<{ id: string }>();
  const providerQuery = trpc.serviceProviders.byId.useQuery({ id: id ?? "" }, { enabled: Boolean(id), retry: false });
  const provider = providerQuery.data;

  return <div className="min-h-screen bg-[#F8FAF6]" dir="rtl"><Navbar /><main className="mx-auto w-full max-w-5xl px-4 py-7 sm:px-6 sm:py-10">{providerQuery.isLoading ? <div className="h-64 animate-pulse rounded-3xl bg-white" /> : !provider ? <section className="mx-auto flex min-h-[45vh] max-w-xl flex-col items-center justify-center rounded-3xl border border-dashed border-[#C9D8C6] bg-white p-8 text-center"><UserRound className="h-10 w-10 text-[#5A866B]" /><h1 className="mt-4 text-xl font-black text-[#193C2A]">مقدم الخدمة غير متاح</h1><p className="mt-2 text-sm leading-7 text-[#65736B]">لا يوجد ملف خدمة معتمد بهذا الرابط أو أن الملف لم يعد منشوراً.</p><Link href="/booking" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#1F4D3A] px-4 py-3 text-sm font-black text-white"><ArrowRight className="h-4 w-4" />العودة إلى الخدمات</Link></section> : <><Link href="/booking" className="inline-flex items-center gap-2 text-sm font-bold text-[#2A6B4F]"><ArrowRight className="h-4 w-4" />كل الخدمات</Link><article className="mt-5 rounded-3xl border border-[#DCE8DA] bg-white p-5 sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-start"><div className="grid h-20 w-20 shrink-0 place-items-center overflow-hidden rounded-2xl bg-[#EEF7EC] text-[#2A6B4F]">{provider.logoUrl ? <img src={provider.logoUrl} alt="" className="h-full w-full object-cover" /> : <UserRound className="h-9 w-9" />}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-black text-[#193C2A]">{provider.name}</h1>{provider.verified && <span className="inline-flex items-center gap-1 rounded-full bg-[#EDF8EC] px-2.5 py-1 text-xs font-bold text-[#1F6B45]"><ShieldCheck className="h-3.5 w-3.5" />معتمد</span>}</div><p className="mt-2 text-sm font-semibold text-[#5A866B]">{provider.category}</p><p className="mt-2 flex items-center gap-1.5 text-sm text-[#65736B]"><MapPin className="h-4 w-4" />{provider.location}</p>{provider.description ? <p className="mt-5 max-w-2xl text-sm leading-8 text-[#46584D]">{provider.description}</p> : <p className="mt-5 text-sm text-[#718078]">لم يضف مقدم الخدمة وصفاً تفصيلياً بعد.</p>}<p className="mt-5 text-xs leading-6 text-[#718078]">لا تعرض هذه الصفحة سعراً أو تقييماً أو سجل إنجازات حتى تُسجل بيانات فعلية قابلة للتحقق.</p><div className="mt-6 flex flex-wrap gap-3"><Link href={`/booking?provider=${provider.id}`} className="rounded-xl bg-[#1F4D3A] px-4 py-3 text-sm font-black text-white">إرسال طلب خدمة</Link><Link href={`/dashboard/messages?provider=${provider.id}`} className="inline-flex items-center gap-2 rounded-xl border border-[#C9D8C6] px-4 py-3 text-sm font-black text-[#1F4D3A]"><MessageCircle className="h-4 w-4" />مراسلة مقدم الخدمة</Link></div></div></div></article></>}</main><Footer /></div>;
}
